
version : '3.7'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: tsCz6fmhAJErn3R
      MYSQL_DATABASE: hermesDb
    ports:
      - "3306:3306"
  backend:
   build: ./api
   command: npm run start:dev
   volumes:
     - ./api:/usr/src/app
   ports:
     - "3000:3000"
   depends_on:
     - mysql
volumes:
 todo-mysql-data: