name: Karma Tests

# Executa apenas em Pull Requests para a branch $branch
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Configuração do Job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Faz checkout do repositório
      - uses: actions/setup-node@v1 # Configura o Node.js
        with:
          node-version: '18.15.0'
      - name: Executa Testes Karma
        run: |
          cd front-desktop
          npm install
          npm run test:ci